[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:refiller]
command=python run_refiller.py
directory=/Users/cbenalcazar/PycharmProjects/ScraperSenescyt
autostart=true
autorestart=true
numprocs=1
stdout_logfile=/var/log/senescyt_refiller.log
stderr_logfile=/var/log/senescyt_refiller_err.log

[program:worker]
command=python run_worker.py
directory=/Users/cbenalcazar/PycharmProjects/ScraperSenescyt
autostart=true
autorestart=true
numprocs=5                          ; cambia este número para escalar
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/var/log/senescyt_worker.log
stderr_logfile=/var/log/senescyt_worker_err.log
